got fields to be filtered before being returned from mailchimp
singer-io/tap-mailchimp pull request #29
Opened 2020-09-03 21:08 UTC by jacobrobertbaca

# Description of change
got fields to be filtered before being returned from mailchimp
https://stitchdata.atlassian.net/secure/RapidBoard.jspa?rapidView=9&projectKey=SRCE&modal=detail&selectedIssue=SRCE-3517
Previously, we were filtering out after a response was returned from mailchimp.
Now, when we add fields to the 'fields' parameter, mailchimp will only return us the fields we ask for,
We had to modify the general sync_endpoint function as well as the sync_email_activity function, since the general calls a different batch endpoint.

# Manual QA steps
 - added fields 'fields' param for each stream
 - checked directly on response object to make sure only requested fields came through
 - ran sync for all streams and made sure the records went through fine
 - IMPORTANT TO NOTE: we weren't able to check that records came through for automations and list_members, since we don't have data for those, but we did follow the same pattern that all the other streams followed for naming the fields.
 
# Risks
 - low
 
# Rollback steps
 - revert this branch

2020-09-04 18:03 UTC, luandy64 commented
This incorporates #23 so we can close #23 when this gets merged

2020-09-08 14:10 UTC, KAllan357 commented on tap_mailchimp/sync.py
> +        field_names = ['emails.'+str(x) for x in selected_fields]+['_links', 'total_items', 'constraints','emails.'+str('_links')]
This could be moved into `get_selected_fields` and be clarified with its intent. Like adding the "top level fields"

2020-09-08 14:11 UTC, KAllan357 requested changes

2020-09-08 14:11 UTC, KAllan357 commented on tap_mailchimp/sync.py
> +def get_selected_fields(catalog, stream_name):
Should use singer-python library calls to get the metadata and check if a field is selected. Should be put under test as well or commented to explain what its doing.

2020-09-08 20:05 UTC, KAllan357 approved these changes

2020-09-09 14:52 UTC, merged